//! Clone orchestration logic.
//!
//! Coordinates the full lifecycle of spawning a child instance on Railway:
//! service creation, environment configuration, Docker image deployment,
//! volume attachment, domain assignment, and deployment trigger.

use crate::railway::{RailwayClient, RailwayError};
use serde::{Deserialize, Serialize};

/// Configuration for clone operations.
#[derive(Clone, Debug)]
pub struct CloneConfig {
    /// Docker image to deploy (e.g., `ghcr.io/compusophy/tempo-x402:latest`)
    pub docker_image: String,
    /// RPC URL for the Tempo chain
    pub rpc_url: String,
    /// URL of this (parent) instance, so children can register back
    pub self_url: String,
    /// Maximum number of children this instance can spawn
    pub max_children: u32,
    /// CPU limit for child instances in millicores (default: 2000 = 2 vCPU)
    pub clone_cpu_millicores: u32,
    /// Memory limit for child instances in MB (default: 2048 = 2GB)
    pub clone_memory_mb: u32,
    /// Extra env vars to inject into children (e.g., soul config)
    pub child_env_vars: std::collections::HashMap<String, String>,
}

/// Result of a successful clone operation.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CloneResult {
    /// Unique ID for the child instance
    pub instance_id: String,
    /// Public URL of the child (Railway domain)
    pub url: String,
    /// Railway service ID
    pub railway_service_id: String,
    /// Railway deployment ID
    pub deployment_id: String,
}

#[derive(Debug, thiserror::Error)]
pub enum CloneError {
    #[error("Railway API error: {0}")]
    Railway(#[from] RailwayError),

    #[error("clone limit reached: {current}/{max} children")]
    LimitReached { current: u32, max: u32 },

    #[error("clone error: {0}")]
    Other(String),
}

/// Orchestrates the clone flow: create service, configure, deploy.
pub struct CloneOrchestrator {
    railway: RailwayClient,
    config: CloneConfig,
}

impl CloneOrchestrator {
    pub fn new(railway: RailwayClient, config: CloneConfig) -> Self {
        Self { railway, config }
    }

    /// Spawn a new child clone on Railway.
    ///
    /// Creates a service, then configures and deploys it. If any step after
    /// service creation fails, the service is cleaned up before returning the error.
    ///
    /// The `instance_id` should be pre-generated by the caller (e.g., after
    /// reserving a DB slot) so the same ID is used throughout the flow.
    pub async fn spawn_clone(
        &self,
        instance_id: &str,
        parent_address: &str,
    ) -> Result<CloneResult, CloneError> {
        let service_name = format!("x402-{}", &instance_id[..8]);

        tracing::info!(
            instance_id = %instance_id,
            service_name = %service_name,
            "Spawning clone"
        );

        // 1. Create service
        let service_id = self.railway.create_service(&service_name).await?;
        tracing::info!(service_id = %service_id, "Railway service created");

        // All subsequent steps run with cleanup-on-failure
        match self
            .spawn_clone_inner(&service_id, instance_id, parent_address)
            .await
        {
            Ok(result) => Ok(result),
            Err(e) => {
                tracing::error!(
                    service_id = %service_id,
                    error = %e,
                    "Clone failed after service creation, cleaning up Railway service"
                );
                if let Err(cleanup_err) = self.railway.delete_service(&service_id).await {
                    tracing::error!(
                        service_id = %service_id,
                        error = %cleanup_err,
                        "Cleanup of Railway service failed"
                    );
                } else {
                    tracing::info!(service_id = %service_id, "Railway service cleaned up");
                }
                Err(e)
            }
        }
    }

    /// Inner clone steps after service creation. Separated so spawn_clone()
    /// can clean up the service if any of these fail.
    async fn spawn_clone_inner(
        &self,
        service_id: &str,
        instance_id: &str,
        parent_address: &str,
    ) -> Result<CloneResult, CloneError> {
        // 2. Get default environment
        let env_id = self.railway.get_default_environment().await?;

        // 3. Set environment variables
        let mut env_map = serde_json::Map::new();
        env_map.insert("AUTO_BOOTSTRAP".into(), "true".into());
        env_map.insert("INSTANCE_ID".into(), instance_id.into());
        env_map.insert("PARENT_URL".into(), self.config.self_url.clone().into());
        env_map.insert("PARENT_ADDRESS".into(), parent_address.into());
        env_map.insert("IDENTITY_PATH".into(), "/data/identity.json".into());
        env_map.insert("DB_PATH".into(), "/data/gateway.db".into());
        env_map.insert("NONCE_DB_PATH".into(), "/data/x402-nonces.db".into());
        env_map.insert("RPC_URL".into(), self.config.rpc_url.clone().into());
        env_map.insert("SPA_DIR".into(), "/app/spa".into());
        env_map.insert("PORT".into(), "4023".into());

        // Inject extra env vars (soul config, API keys, etc.)
        for (key, value) in &self.config.child_env_vars {
            env_map.insert(key.clone(), value.clone().into());
        }

        let env_vars = serde_json::Value::Object(env_map);
        self.railway
            .set_variables(service_id, &env_id, env_vars)
            .await?;
        tracing::info!("Environment variables configured");

        // 4. Set Docker image
        self.railway
            .set_docker_image(service_id, &self.config.docker_image)
            .await?;
        tracing::info!(image = %self.config.docker_image, "Docker image set");

        // 5. Add volume
        self.railway
            .add_volume(service_id, &env_id, "/data")
            .await?;
        tracing::info!("Volume attached at /data");

        // 6. Set resource limits (conservative defaults for children)
        if self.config.clone_cpu_millicores > 0 || self.config.clone_memory_mb > 0 {
            self.railway
                .update_service_resources(
                    service_id,
                    &env_id,
                    self.config.clone_cpu_millicores,
                    self.config.clone_memory_mb,
                )
                .await?;
            tracing::info!(
                cpu = self.config.clone_cpu_millicores,
                memory_mb = self.config.clone_memory_mb,
                "Resource limits configured"
            );
        }

        // 7. Create domain
        let url = self.railway.create_domain(service_id, &env_id).await?;
        tracing::info!(url = %url, "Domain created");

        // 8. Deploy
        let deployment_id = self.railway.deploy_service(service_id, &env_id).await?;
        tracing::info!(deployment_id = %deployment_id, "Deployment triggered");

        Ok(CloneResult {
            instance_id: instance_id.to_string(),
            url,
            railway_service_id: service_id.to_string(),
            deployment_id,
        })
    }

    /// Redeploy an existing clone service by re-pulling the `:latest` image.
    ///
    /// Fetches the default environment, then triggers `serviceInstanceDeploy`
    /// which re-pulls the Docker image and restarts the service.
    pub async fn redeploy_clone(&self, service_id: &str) -> Result<String, CloneError> {
        let env_id = self.railway.get_default_environment().await?;
        let result = self.railway.deploy_service(service_id, &env_id).await?;
        Ok(result)
    }

    /// Delete a Railway service. Delegates to the Railway client.
    pub async fn delete_service(&self, service_id: &str) -> Result<(), CloneError> {
        self.railway.delete_service(service_id).await?;
        Ok(())
    }

    pub fn config(&self) -> &CloneConfig {
        &self.config
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_clone_config() {
        let config = CloneConfig {
            docker_image: "ghcr.io/compusophy/tempo-x402:latest".to_string(),
            rpc_url: "https://rpc.moderato.tempo.xyz".to_string(),
            self_url: "https://my-instance.up.railway.app".to_string(),
            max_children: 10,
            clone_cpu_millicores: 2000,
            clone_memory_mb: 2048,
            child_env_vars: std::collections::HashMap::new(),
        };
        assert_eq!(config.max_children, 10);
        assert_eq!(config.clone_cpu_millicores, 2000);
    }

    #[test]
    fn test_clone_error_display() {
        let err = CloneError::LimitReached {
            current: 10,
            max: 10,
        };
        assert!(err.to_string().contains("10/10"));
    }
}
